backend:
  name: github
  repo: shaunsonggit/ComfyUI-Beginners-Guide
  branch: main
  open_authoring: true
  commit_messages:
    create: "feat(cms): create {{collection}} {{slug}}"
    update: "chore(cms): update {{collection}} {{slug}}"
    delete: "chore(cms): delete {{collection}} {{slug}}"
    uploadMedia: "chore(cms): upload media"
    deleteMedia: "chore(cms): delete media"
media_folder: public/assets/uploads
public_folder: /assets/uploads
publish_mode: editorial_workflow
local_backend: true
slug:
  clean_accents: true
  encoding: unicode
  sanitize_replacement: "-"
collections:
  - name: tutorial
    label: 教程章节
    label_singular: 章节
    folder: src/content/tutorial
    extension: mdx
    format: frontmatter
    create: true
    slug: "{{slug}}"
    preview_path: tutorial/{{slug}}/
    summary: "第{{order}}章 · {{title}}"
    sortable_fields: [order, title]
    editor:
      preview: false
    fields:
      - { name: title, label: 标题, widget: string }
      - { name: description, label: 摘要, widget: text }
      - { name: order, label: 排序序号, widget: number, value_type: int }
      - name: heroImage
        label: 章节主图
        widget: image
        required: false
        allow_multiple: false
      - name: gifDemo
        label: 动图演示
        widget: image
        required: false
        allow_multiple: false
      - name: keywords
        label: 关键词标签
        widget: list
        allow_add: true
        default: []
        field:
          name: keyword
          label: 标签名
          widget: string
      - { name: goal, label: 学习目标, widget: string, required: false }
      - { name: duration, label: 时间预估, widget: string, required: false }
      - { name: difficulty, label: 难度, widget: string, required: false }
      - name: prerequisites
        label: 前置准备
        widget: list
        allow_add: true
        default: []
        field:
          name: prerequisite
          label: 条目
          widget: string
      - name: deliverables
        label: 产出物
        widget: list
        allow_add: true
        default: []
        field:
          name: deliverable
          label: 条目
          widget: string
      - name: pitfalls
        label: 易错提醒
        widget: list
        allow_add: true
        default: []
        field:
          name: pitfall
          label: 条目
          widget: string
      - label: 操作按钮
        name: ctaButtons
        widget: list
        required: false
        collapsed: true
        summary: "{{fields.label}} → {{fields.url}}"
        fields:
          - { label: 按钮文案, name: label, widget: string }
          - { label: 链接地址, name: url, widget: string }
          - { label: 下载文件？, name: download, widget: boolean, default: false }
      - { name: body, label: 正文内容, widget: markdown }
  - name: site
    label: 站点配置
    files:
      - label: 资源配置
        name: resources
        file: src/content/site/resources.json
        format: json
        fields:
          - label: 资源速达
            name: quickLinks
            widget: object
            fields:
              - { label: 是否显示, name: enabled, widget: boolean, default: true }
              - { label: 标题, name: title, widget: string, default: "资源速达" }
              - label: 链接列表
                name: items
                widget: list
                allow_add: true
                fields:
                  - { label: 文案, name: label, widget: string }
                  - { label: 链接地址, name: url, widget: string }
                  - { label: 新窗口打开?, name: external, widget: boolean, default: false }
                  - { label: 图标(可选), name: icon, widget: string, required: false }
          - label: 配套资源
            name: downloads
            widget: object
            fields:
              - { label: 是否显示, name: enabled, widget: boolean, default: true }
              - { label: 标题, name: title, widget: string, default: "配套资源下载" }
              - { label: 描述(可选), name: description, widget: text, required: false }
              - label: 下载项
                name: items
                widget: list
                allow_add: true
                fields:
                  - { label: 文案, name: label, widget: string }
                  - { label: 链接地址, name: url, widget: string }
                  - { label: 下载文件?, name: download, widget: boolean, default: false }
